mysite/auth/urls.py
from django.contrib.auth import views
from django.urls import path

from .forms import MyLoginForm
from .views import SignUpView

app_name = "auth"


urlpatterns = [
    path(
        "login/",
        views.LoginView.as_view(
            template_name="auth/login.html",
            form_class=MyLoginForm,
        ),
        name="login",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(template_name="auth/logout.html"),
        name="logout",
    ),
    path(
        "signup/",
        SignUpView.as_view(),
        name="signup",
    ),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path("admin", admin.site.urls),
    path("auth/", include("auth.urls")),
    path("", include("homepage.urls")),
    path("services/", include("services.urls")),
    path("reviews/", include("reviews.urls")),
    path("user/", include("user.urls")),
    path("about/", include("about.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/services/urls.py
from django.urls import path
from .views import services, detail, booking

app_name = "services"

urlpatterns = [
    path("", services, name="services"),
    path("detail/<int:id>/", detail, name="detail"),
    path("booking/<int:id>/", booking, name="booking"),
]

mysite/user/urls.py
from django.urls import path

from .views import delete_booking, update_image, user

app_name = "user"

urlpatterns = [
    path("", user, name="user"),
    path("delete_booking/", delete_booking, name="delete_booking"),
    path("update_image/", update_image, name="update_image"),
]

mysite/user/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.safestring import mark_safe
from django.conf import settings
from uuid import uuid4
from sorl.thumbnail import get_thumbnail

import os


class Profile(models.Model):
    """Класс профиля"""
    def upload_to(self, filename):
        email = self.user.email
        file_name, file_extension = os.path.splitext(filename)
        filename = f"{uuid4().hex}{file_extension}"
        return "images/{0}/{1}".format(email, filename)

    def user_email(self):
        return self.user.email

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(
        "фотография",
        upload_to=upload_to,
        null=True,
        blank=True,
    )

    def get_image_300x300(self):
        return get_thumbnail(
            self.image,
            "50x50",
            quality=100,
        )

    def image_tmb(self):
        if self.image:
            return mark_safe(
                f"<img src='{self.get_image_300x300().url}' "
                f"width='50' "
                f"height='50'>"
            )
        return "Нет изображения"

    class Meta:
        verbose_name = "профиль"
        verbose_name_plural = "профиля"

        db_table = "profiles"

    def __str__(self):
        return f"{self.user}"

    def update(self):
        BASE_DIR = settings.BASE_DIR

        email = self.user_email()
        try:
            path_to_directory = os.path.join(
                BASE_DIR, "media", "images", email
            )
            for filename in os.listdir(path_to_directory):
                path_to_file = os.path.join(path_to_directory, filename)
                os.remove(path_to_file)
        except Exception as e:
            pass


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

mysite/user/forms.py
from django import forms

from mysite.mixins import BaseFormMixin
from .models import Profile


class ProfileImageForm(BaseFormMixin, forms.ModelForm):
    """Клас, отвечающий за форму изменения изображения"""
    class Meta:
        model = Profile
        fields = ["image"]

mysite/user/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import JsonResponse
from django.utils import timezone

from services.models import Booking
from .forms import ProfileImageForm
from .models import Profile


def user(request):
    """Функция, отвечающая за страничку 'Профиль'"""
    template_dir = "user/user.html"

    user = request.user

    if user.is_authenticated:
        profile = get_object_or_404(Profile, user=user)

        bookings_past = Booking.objects.filter(
            user=user, datetime__lte=timezone.now()
        ).order_by("-datetime")

        bookings_future = Booking.objects.filter(
            user=user, datetime__gte=timezone.now()
        ).order_by("-datetime")

        context = {
            "profile": profile,
            "bookings_past": bookings_past,
            "bookings_future": bookings_future,
        }

        return render(request, template_dir, context=context)
    return redirect("auth:login")


def delete_booking(request):
    """Функция, отвечающая за удаления брони"""
    id = int(request.POST.get("id"))

    booking = Booking.objects.get(id=id)
    booking.delete()

    return JsonResponse({"error": "OK"}, status=200)


def update_image(request):
    """Функция, отвечающая за страничку 'Смена фотографии"""
    template_dir = "user/update_image.html"

    if request.user.is_authenticated:
        profile = request.user.profile

        if request.method == "POST":
            form = ProfileImageForm(
                request.POST, request.FILES, instance=profile
            )
            if form.is_valid():
                profile.update()
                form.save()
                return redirect("user:user")
        else:
            form = ProfileImageForm(instance=profile)

        context = {"form": form}

        return render(request, template_dir, context=context)
    return redirect("auth:login")

mysite/templates/user/update_image.html
{% extends "base.html" %}

{% block title %}
    Замена фотографии
{% endblock %}

{% block body %}
    {% load static %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2 class="my-4">Замена фотографии</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.image }}
                    </div>
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

mysite/templates/user/user.html
{% extends "base.html" %}

{% block title %}
  Профиль
{% endblock %}

{% block body %}
  {% load static %}
  <div class="container bootstrap snippets bootdey">
    <div class="profile card">
      <div class="profile-body">
        <div class="profile-bio">
          <div class="row">
            <div class="col-md-5 text-center">
              {% if profile.image %}
                <img style="width: 400px; height:400px;" class="img-thumbnail md-margin-bottom-10"
                     src="{{ profile.image.url }}" alt="">
              {% else %}
                <img style="width: 400px; height:400px;" class="img-thumbnail md-margin-bottom-10"
                     src="{% static 'img/no_image.png' %}" alt="">
              {% endif %}
              <a class="btn btn-outline-primary"
                 style="margin-top: 18px; margin-bottom: 15px; margin-right: 15px; width: 150px;"
                 href="{% url 'user:update_image' %}">Изменить фото</a>
              <a class="btn btn-outline-primary" style="margin-top: 18px; margin-bottom: 15px; width: 150px;"
                 href="{% url 'services:services' %}">К услугам</a>
            </div>
            <div class="col-md-7">
              <h2>{{ profile.user }}</h2>
              <span><strong>Почта:</strong> {{ profile.user.email }}</span>
              <span><strong>Роль:</strong> {% if user.is_superuser %}Админ{% else %}Пользователь{% endif %}</span>
              <hr>
              <ul>
                {% for booking in bookings_future %}
                  <li style="background-color: #c2ff66; border-radius: 0 10px; padding: 10px; margin-bottom: 10px; display: flex; justify-content: space-between; align-items: center;">
                    <div>
                      <span style="font-size: 110%;"><strong>{{ booking.service.title }}</strong></span><br>
                      на {{ booking.datetime }}
                    </div>
                    <button class="btn btn-outline-primary" onclick="delete_booking({{ booking.id }})">Удалить</button>
                  </li>
                {% endfor %}

                {% for booking in bookings_past %}
                  <li style="background-color: #b9bdb3; border-radius: 0 10px; padding: 10px; margin-bottom: 10px; display: flex; justify-content: space-between; align-items: center;">
                    <div>
                      <span style="font-size: 110%;"><strong>{{ booking.service.title }}</strong></span><br>
                      на {{ booking.datetime }}
                    </div>
                    <button class="btn btn-outline-primary" onclick="delete_booking({{ booking.id }})">Удалить</button>
                  </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br><br><br><br><br>
<script>
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

function delete_booking(id) {
  var csrftoken = getCookie('csrftoken');
  $.ajax({
          url: 'delete_booking/',
          type: 'POST',
          headers: {
              'X-CSRFToken': csrftoken
          },
          data: {
              id: Number(id),
          },
          success: function () {
            location.reload()
          },
      })
}
</script>
{% endblock %}