mysite/about/urls.py
from django.urls import path

from .views import about

app_name = "about"

urlpatterns = [
    path("", about, name="about")
]

mysite/auth/urls.py
from django.contrib.auth import views
from django.urls import path

from .forms import MyLoginForm
from .views import SignUpView

app_name = "auth"


urlpatterns = [
    path(
        "login/",
        views.LoginView.as_view(
            template_name="auth/login.html",
            form_class=MyLoginForm,
        ),
        name="login",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(template_name="auth/logout.html"),
        name="logout",
    ),
    path(
        "signup/",
        SignUpView.as_view(),
        name="signup",
    ),
]

mysite/homepage/urls.py
from django.urls import path
from .views import homepage

app_name = "homepage"

urlpatterns = [
    path("", homepage, name="homepage"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path("admin", admin.site.urls),
    path("auth/", include("auth.urls")),
    path("", include("homepage.urls")),
    path("services/", include("services.urls")),
    path("reviews/", include("reviews.urls")),
    path("user/", include("user.urls")),
    path("about/", include("about.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/reviews/urls.py
from django.urls import path
from .views import reviews

app_name = "reviews"

urlpatterns = [
    path("", reviews, name="reviews"),
]

mysite/services/urls.py
from django.urls import path
from .views import services, detail, booking

app_name = "services"

urlpatterns = [
    path("", services, name="services"),
    path("detail/<int:id>/", detail, name="detail"),
    path("booking/<int:id>/", booking, name="booking"),
]

mysite/homepage/views.py
from django.shortcuts import render


def homepage(request):
    """Функция, отвечающая за страничку 'Главная'"""
    template_dir = "homepage/homepage.html"

    context = {}

    return render(request, template_dir, context=context)

mysite/templates/homepage/homepage.html
{% extends "base.html" %}

{% block title %}
  Главная
{% endblock %}

{% block body %}
  {% load static %}

  <section style="width: 900px; height: 60vh; margin: auto; margin-top: 90px;">
    <div style="display: flex; justify-content: space-between;">
      <div style="width: 60%;">
      <h1 style="font-size: 40px; font-weight: bold;">Бест Клиник</h1>
      <p style="font-size: 20px;"><strong>Мы поможем вам разобраться в ситуации!</strong><br>Благодаря нашим диагностическим процедурам на передовом японском оборудовании, вы получите высококачественную диагностику в различных областях.</p>
      <div style="margin-top: 40px;">
        <a class="btn btn-outline-primary" style="width: 110px;" href="{% url 'services:services' %}">Услуги</a>
        <a class="btn btn-outline-success" style="width: 110px;" href="{% url 'reviews:reviews' %}">Отзывы</a>
        <a class="btn btn-outline-info" style="width: 110px;" href="{% url 'about:about' %}">О нас</a>
      </div>
      </div>
      <div style="">
        <img src="{% static 'img/image.png' %}" style="object-fit: cover; width: 320px; height: 320px;">
      </div>
    </div>
  </section>
{% endblock %}