mysite/auth/urls.py
from django.contrib.auth import views
from django.urls import path

from .forms import MyLoginForm
from .views import SignUpView

app_name = "auth"


urlpatterns = [
    path(
        "login/",
        views.LoginView.as_view(
            template_name="auth/login.html",
            form_class=MyLoginForm,
        ),
        name="login",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(template_name="auth/logout.html"),
        name="logout",
    ),
    path(
        "signup/",
        SignUpView.as_view(),
        name="signup",
    ),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path("admin", admin.site.urls),
    path("auth/", include("auth.urls")),
    path("", include("homepage.urls")),
    path("services/", include("services.urls")),
    path("reviews/", include("reviews.urls")),
    path("user/", include("user.urls")),
    path("about/", include("about.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/services/urls.py
from django.urls import path
from .views import services, detail, booking

app_name = "services"

urlpatterns = [
    path("", services, name="services"),
    path("detail/<int:id>/", detail, name="detail"),
    path("booking/<int:id>/", booking, name="booking"),
]

mysite/services/models.py
from django.db import models
from django.contrib.auth.models import User


class Service(models.Model):
    """Класс услуг"""
    title = models.CharField(
        verbose_name="заголовок",
        null=False,
        validators=[],
        max_length=64
    )
    text = models.TextField(
        verbose_name="описание",
        default="отсутствует",
    )
    price = models.DecimalField(
        verbose_name="цена",
        max_digits=10,
        decimal_places=2,
    )

    class Meta:
        verbose_name = "услуга"
        verbose_name_plural = "услуги"

        db_table = "services"

    def __str__(self):
        return f"{self.title} is {self.text}"


class Booking(models.Model):
    """Класс брони"""
    service = models.ForeignKey(
        Service,
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    datetime = models.DateTimeField(
        "Дата и время записи",
    )

    class Meta:
        verbose_name = "бронь"
        verbose_name_plural = "брони"

        db_table = "bookings"

    def __str__(self):
        return (
            f"Запись {self.user} на {self.datetime.strftime('%d-%m-%Y %H:%M')}"
        )

mysite/services/forms.py
from django import forms
from django.utils import timezone

from .models import Booking


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ["datetime"]
        widgets = {
            "datetime": forms.DateTimeInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "ДД-ММ-ГГГГ ЧЧ:ММ",
                },
                format="%d-%m-%Y %H:%M",
            ),
        }

mysite/services/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Service, Booking

from datetime import datetime, timedelta


def services(request):
    """Функция, отвечающая за страничку 'Услуги'"""
    template_dir = "services/services.html"

    services = Service.objects.all()

    context = {
        "services": services
    }

    return render(request, template_dir, context=context)


def detail(request, id):
    """Функция, отвечающая за страничку 'Об услуге'"""
    template_dir = "services/detail.html"

    service = get_object_or_404(Service, id=id)

    context = {
        "service": service,
    }

    return render(request, template_dir, context=context)


def booking(request, id):
    """Функция, отвечающая за страничку 'Бронь'"""
    template_dir = "services/booking.html"

    service = get_object_or_404(Service, id=id)
    user = request.user

    if user.is_authenticated:
        current_datetime = datetime.now()
        one_hour_later = current_datetime + timedelta(hours=1)
        one_month_later = current_datetime + timedelta(days=30)

        if request.method == "POST":
            datetime_str = request.POST.get("datetime")
            datetime_ = datetime.strptime(datetime_str, "%Y-%m-%dT%H:%M")
            if datetime_ > current_datetime:
                book_obj = Booking(
                    service=service,
                    user=user,
                    datetime=datetime_
                )
                book_obj.save()
                return redirect("user:user")
            return redirect("services:booking", id=service.id)

        context = {
            "service": service,
            "datetime_value": one_hour_later.strftime("%Y-%m-%d %H:%M"),
            "min_date": current_datetime.strftime("%Y-%m-%d %H:%M"),
            "max_date": one_month_later.strftime("%Y-%m-%d %H:%M"),
        }

        return render(request, template_dir, context=context)
    return redirect("auth:login")

mysite/templates/services/booking.html
{% extends "base.html" %}

{% block title %}
  Бронь
{% endblock %}

{% block body %}
  {% load static %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <h2>Запись на <strong>{{ service.title }}</strong></h2>
        <form method="post">
          {% csrf_token %}
          <div class="form-group" style="margin-top: 20px; margin-bottom: 20px;">
            <input
                    type="datetime-local"
                    id="datetime"
                    name="datetime"
                    value="{{ datetime_value }}"
                    min="{{ min_date }}"
                    max="{{ max_date }}"
            />
          </div>
          <button type="submit" class="btn btn-primary">Записаться</button>
        </form>
        <p style="margin-top: 10px;">Пример формата: ДД-ММ-ГГГГ ЧЧ:ММ</p>
      </div>
    </div>
  </div>
{% endblock %}

mysite/templates/services/detail.html
{% extends "base.html" %}

{% block title %}
  Об услуге
{% endblock %}

{% block body %}
  {% load static %}
  <div class="card text-center" style="width: 55%; margin-left: auto; margin-right: auto; margin-top: 20px">
    <div class="card-header">
      <p style="max-height: 5px;"></p>
    </div>
    <div class="card-body">
      <h5 class="card-title">Название услуги: <b>{{ service.title }}</b></h5>
      <p class="card-text">Описание услуги: <i>{{ service.text }}</i></p>
    </div>
    <div class="card-footer text-muted">
      {{ service.price }} / услуга
    </div>
    {% if request.user.is_authenticated %}
    <a class="btn btn-outline-primary" style="width: 200px; margin: auto; margin-top: 10px; margin-bottom: 10px;" href="{% url 'services:booking' service.id %}">
      Записаться
    </a>
    {% endif %}
  </div>
{% endblock %}

mysite/templates/services/services.html
{% extends "base.html" %}

{% block title %}
  Услуги
{% endblock %}

{% block body %}
  {% load static %}
  <section style="width: 92%; margin-left: auto; margin-right: auto; margin-top: 30px; margin-bottom: 100px;">
    <ol class="list-group list-group-numbered">
      {% for service in services %}
        <a href="{% url 'services:detail' service.id %}" style="text-decoration: none;">
          <li class="list-group-item d-flex justify-content-between align-items-start" style="margin-top: 5px; margin-bottom: 5px;">
          <div class="ms-2 me-auto">
            <div>Название услуги: <b>{{ service.title }}</b></div>
            Описание услуги: <i>{{ service.text }}</i>
          </div>
          <span class="badge bg-primary rounded-pill">{{ service.price }}</span>
          </li>
        </a>
      {% endfor %}
    </ol>
    <br><br><br><br><br><br><br><br>
  </section>
{% endblock %}