mysite/about/urls.py
from django.urls import path

from .views import about

app_name = "about"

urlpatterns = [
    path("", about, name="about")
]

mysite/auth/urls.py
from django.contrib.auth import views
from django.urls import path

from .forms import MyLoginForm
from .views import SignUpView

app_name = "auth"


urlpatterns = [
    path(
        "login/",
        views.LoginView.as_view(
            template_name="auth/login.html",
            form_class=MyLoginForm,
        ),
        name="login",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(template_name="auth/logout.html"),
        name="logout",
    ),
    path(
        "signup/",
        SignUpView.as_view(),
        name="signup",
    ),
]

mysite/homepage/urls.py
from django.urls import path
from .views import homepage

app_name = "homepage"

urlpatterns = [
    path("", homepage, name="homepage"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path("admin", admin.site.urls),
    path("auth/", include("auth.urls")),
    path("", include("homepage.urls")),
    path("services/", include("services.urls")),
    path("reviews/", include("reviews.urls")),
    path("user/", include("user.urls")),
    path("about/", include("about.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/reviews/urls.py
from django.urls import path
from .views import reviews

app_name = "reviews"

urlpatterns = [
    path("", reviews, name="reviews"),
]

mysite/user/urls.py
from django.urls import path

from .views import delete_booking, update_image, user

app_name = "user"

urlpatterns = [
    path("", user, name="user"),
    path("delete_booking/", delete_booking, name="delete_booking"),
    path("update_image/", update_image, name="update_image"),
]

mysite/templates/includes/footer.html
<footer class="bg-body-tertiary text-center text-lg-start">
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
    <p>&copy; {% now "Y" %} Бест Клиник. Все права защищены.</p>
  </div>
</footer>

mysite/templates/includes/form.html
{% for field in form %}
  <div class="form-group mb-3">
    <label for="{{ field.auto_id }}" class="form-label">{{ field.label }}</label>
    {{ field }}
    {% if field.errors %}
      {% for error in field.errors %}
        <div class="invalid-feedback">
          {{ error|safe }}
        </div>
      {% endfor %}
    {% endif %}
    {% if field.help_text %}
      <div class="form-text text-muted">
        <p>{{ field.help_text|safe }}</p>
      </div>
    {% endif %}
  </div>
{% endfor %}
{% if form.non_field_errors %}
  <div class="alert alert-danger">
    {% for error in form.non_field_errors %}
      {{ error|safe }}
    {% endfor %}
  </div>
{% endif %}

mysite/templates/includes/header.html
{% load static %}
<header class="d-flex justify-content-center py-3">
  <ul class="nav nav-pills">
    {% with request.resolver_match.view_name as view_name %}
      <li class="nav-item"><a href="{% url 'homepage:homepage' %}" class="nav-link {% if view_name == 'homepage:homepage' %}active{% endif %}" aria-current="page">
        Главная
      </a></li>
      <li class="nav-item"><a href="{% url 'services:services' %}" class="nav-link {% if view_name == 'services:services' %}active{% endif %}" aria-current="page">
        Услуги
      </a></li>
      <li class="nav-item"><a href="{% url 'reviews:reviews' %}" class="nav-link {% if view_name == 'reviews:reviews' %}active{% endif %}" aria-current="page">
        Отзывы
      </a></li>
      <li class="nav-item"><a href="{% url 'about:about' %}" class="nav-link {% if view_name == 'about:about' %}active{% endif %}" aria-current="page">
        О нас
      </a></li>
      {% if request.user.is_anonymous %}
        <li class="nav-item"><a href="{% url 'auth:login' %}" class="nav-link {% if view_name == 'auth:login' %}active{% endif %}" aria-current="page">
          Войти
        </a></li>
        <li class="nav-item"><a href="{% url 'auth:signup' %}" class="nav-link {% if view_name == 'auth:signup' %}active{% endif %}" aria-current="page">
          Зарегистрироваться
        </a></li>
      {% else %}
        <li class="nav-item"><a href="{% url 'user:user' %}" class="nav-link {% if view_name == 'user:user' %}active{% endif %}" aria-current="page">
          Профиль
        </a></li>
        <li class="nav-item"><a href="{% url 'auth:logout' %}" class="nav-link {% if view_name == 'auth:logout' %}active{% endif %}" aria-current="page">
          Выйти
        </a></li>
      {% endif %}
    {% endwith %}
  </ul>
</header>